#!/bin/bash

MODULE=$(basename $PWD)
QUIET="NO"
while [[ "$1" != "" ]]; do
    case "$1" in
        "-q") QUIET="YES";;
    esac
    shift
done

VERSION=$(cat package.json | grep "version" | sed 's/.*"version": "\(.*\)",$/\1/')
CHANGES=$(git log --oneline "v$VERSION"..master | while read LINE; do echo "    $LINE"; done)

if [[ "$CHANGES" != "" ]]; then
    printf "\nUnpublished changes for $MODULE:\n$CHANGES\n\n"
else
    printf "No unpublished changes for $MODULE\n\n"
fi
